"""add quiz_responses table

Revision ID: 3ec6ffd44724
Revises: c9050becd840
Create Date: 2026-03-14 15:51:17.738537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec6ffd44724'
down_revision: Union[str, Sequence[str], None] = 'c9050becd840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('color_scores', sa.JSON(), nullable=False),
    sa.Column('dominant_color', sa.String(length=20), nullable=False),
    sa.Column('secondary_color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_responses_id'), 'quiz_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_responses_id'), table_name='quiz_responses')
    op.drop_table('quiz_responses')
    # ### end Alembic commands ###
